/**
 * @file GPIO_config.h
 * @author Amr M. Taha (amr.taha1261@gmail.com)
 * @brief this file contians the essential configurations
 *        that is used to initialize the GPIO peripheral's
 *        Register.
 * @version 1
 * @date 2023-09-26
 * 
 * @copyright Copyright (c) 2023
 * 
 */
#ifndef _GPIO_CONFIG_
#define _GPIO_CONFIG_
#include "../../LIB/std_types.h"
#include "GPIO_interface.h"

/******************GPIO Port Enable********************************************/
/**
 * @ref PORT_ENABLE
*/
#define GPIOA_ENABLE    ENABLE_PORT
#define GPIOB_ENABLE    DISABLE_PORT
#define GPIOC_ENABLE    ENABLE_PORT
#define GPIOD_ENABLE    DISABLE_PORT
#define GPIOE_ENABLE    DISABLE_PORT
/***************************** PORT A *****************************************/
/**
 * @ref PORT_MODES
 * SET PORT A PINS CONFIGURATION
 */
#define PORTA_PIN0_MODE GPIO_INPUT
#define PORTA_PIN1_MODE GPIO_INPUT
#define PORTA_PIN2_MODE GPIO_INPUT
#define PORTA_PIN3_MODE GPIO_OUTPUT_50MHZ
#define PORTA_PIN4_MODE GPIO_OUTPUT_50MHZ
#define PORTA_PIN5_MODE GPIO_OUTPUT_2MHZ
#define PORTA_PIN6_MODE GPIO_INPUT
#define PORTA_PIN7_MODE GPIO_INPUT
#define PORTA_PIN8_MODE GPIO_INPUT
#define PORTA_PIN9_MODE GPIO_OUTPUT_10MHZ
#define PORTA_PIN10_MODE GPIO_OUTPUT_2MHZ
#define PORTA_PIN11_MODE GPIO_OUTPUT_50MHZ
#define PORTA_PIN12_MODE GPIO_INPUT
#define PORTA_PIN13_MODE GPIO_INPUT
#define PORTA_PIN14_MODE GPIO_INPUT
#define PORTA_PIN15_MODE GPIO_INPUT

#define PORTA_PIN0_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTA_PIN1_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTA_PIN2_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTA_PIN3_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTA_PIN4_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTA_PIN5_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTA_PIN6_CONFIG GPIO_INPUT_FLOAT
#define PORTA_PIN7_CONFIG GPIO_INPUT_FLOAT
#define PORTA_PIN8_CONFIG GPIO_INPUT_FLOAT
#define PORTA_PIN9_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTA_PIN10_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTA_PIN11_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTA_PIN12_CONFIG GPIO_INPUT_FLOAT
#define PORTA_PIN13_CONFIG GPIO_INPUT_FLOAT
#define PORTA_PIN14_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTA_PIN15_CONFIG GPIO_INPUT_PULLUP_DOWN
/**
 * @ref PIN_LOCKING
 * to lock the pin on it's value (can't be changed until the next reset)
 */
#define PORTA_PIN0_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN1_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN2_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN3_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN4_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN5_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN6_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN7_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN8_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN9_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN10_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN11_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN12_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN13_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN14_LOCK GPIO_PIN_UNLOCKED
#define PORTA_PIN15_LOCK GPIO_PIN_UNLOCKED

/**
 * @ref PORT_VALUES
 * SET PORT A PINS VALUES (IF PIN CONFIGURED AS OUTPUT)
 * or Set Input type (pull up or pull down)
 */
#define PORTA_PIN0_VALUE GPIO_INPUT_PULLDOWN
#define PORTA_PIN1_VALUE GPIO_INPUT_PULLUP
#define PORTA_PIN2_VALUE GPIO_INPUT_PULLDOWN
#define PORTA_PIN3_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN4_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN5_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN6_VALUE GPIO_INPUT_PULLUP
#define PORTA_PIN7_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN8_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN9_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN10_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN11_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN12_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN13_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN14_VALUE GPIO_OUTPUT_HIGH
#define PORTA_PIN15_VALUE GPIO_OUTPUT_HIGH

/***************************** PORT B *****************************************/
/**
 * SET PORT B PINS MODES
 * @ref PORT_MODES
 */
#define PORTB_PIN0_MODE GPIO_OUTPUT_10MHZ
#define PORTB_PIN1_MODE GPIO_OUTPUT_2MHZ
#define PORTB_PIN2_MODE GPIO_INPUT
#define PORTB_PIN3_MODE GPIO_OUTPUT_50MHZ
#define PORTB_PIN4_MODE GPIO_OUTPUT_50MHZ
#define PORTB_PIN5_MODE GPIO_OUTPUT_2MHZ
#define PORTB_PIN6_MODE GPIO_INPUT
#define PORTB_PIN7_MODE GPIO_INPUT
#define PORTB_PIN8_MODE GPIO_INPUT
#define PORTB_PIN9_MODE GPIO_OUTPUT_10MHZ
#define PORTB_PIN10_MODE GPIO_OUTPUT_2MHZ
#define PORTB_PIN11_MODE GPIO_OUTPUT_50MHZ
#define PORTB_PIN12_MODE GPIO_INPUT
#define PORTB_PIN13_MODE GPIO_INPUT
#define PORTB_PIN14_MODE GPIO_INPUT
#define PORTB_PIN15_MODE GPIO_INPUT

/**
 * @ref PORT_CONFIGURATION
 * SET PORT B PINS CONFIGURATION
 */
#define PORTB_PIN0_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTB_PIN1_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTB_PIN2_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTB_PIN3_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTB_PIN4_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTB_PIN5_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTB_PIN6_CONFIG GPIO_INPUT_FLOAT
#define PORTB_PIN7_CONFIG GPIO_INPUT_FLOAT
#define PORTB_PIN8_CONFIG GPIO_INPUT_FLOAT
#define PORTB_PIN9_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTB_PIN10_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTB_PIN11_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTB_PIN12_CONFIG GPIO_INPUT_FLOAT
#define PORTB_PIN13_CONFIG GPIO_INPUT_FLOAT
#define PORTB_PIN14_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTB_PIN15_CONFIG GPIO_INPUT_PULLUP_DOWN

/**
 * @ref PIN_LOCKING
 * to lock the pin on it's value (can't be changed until the next reset)
 */
#define PORTB_PIN0_LOCK GPIO_PIN_LOCKED
#define PORTB_PIN1_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN2_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN3_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN4_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN5_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN6_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN7_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN8_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN9_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN10_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN11_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN12_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN13_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN14_LOCK GPIO_PIN_UNLOCKED
#define PORTB_PIN15_LOCK GPIO_PIN_UNLOCKED

/**
 * @ref PORT_VALUES
 * SET PORT B PINS VALUES (IF PIN CONFIGURED AS OUTPUT)
 */
#define PORTB_PIN0_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN1_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN2_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN3_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN4_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN5_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN6_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN7_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN8_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN9_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN10_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN11_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN12_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN13_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN14_VALUE GPIO_OUTPUT_HIGH
#define PORTB_PIN15_VALUE GPIO_OUTPUT_HIGH
/***************************** PORT C *****************************************/
/**
 * @ref PORT_MODES
 * SET PORT C PINS MODES
 */
#define PORTC_PIN0_MODE GPIO_OUTPUT_10MHZ
#define PORTC_PIN1_MODE GPIO_OUTPUT_2MHZ
#define PORTC_PIN2_MODE GPIO_INPUT
#define PORTC_PIN3_MODE GPIO_OUTPUT_50MHZ
#define PORTC_PIN4_MODE GPIO_OUTPUT_50MHZ
#define PORTC_PIN5_MODE GPIO_OUTPUT_2MHZ
#define PORTC_PIN6_MODE GPIO_INPUT
#define PORTC_PIN7_MODE GPIO_INPUT
#define PORTC_PIN8_MODE GPIO_INPUT
#define PORTC_PIN9_MODE GPIO_OUTPUT_10MHZ
#define PORTC_PIN10_MODE GPIO_OUTPUT_2MHZ
#define PORTC_PIN11_MODE GPIO_OUTPUT_50MHZ
#define PORTC_PIN12_MODE GPIO_INPUT
#define PORTC_PIN13_MODE GPIO_INPUT
#define PORTC_PIN14_MODE GPIO_INPUT
#define PORTC_PIN15_MODE GPIO_INPUT

/**
 * @ref PORT_CONFIGURATION
 * SET PORT C PINS CONFIGURATION
 */
#define PORTC_PIN0_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTC_PIN1_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTC_PIN2_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTC_PIN3_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTC_PIN4_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTC_PIN5_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTC_PIN6_CONFIG GPIO_INPUT_FLOAT
#define PORTC_PIN7_CONFIG GPIO_INPUT_FLOAT
#define PORTC_PIN8_CONFIG GPIO_INPUT_FLOAT
#define PORTC_PIN9_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTC_PIN10_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTC_PIN11_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTC_PIN12_CONFIG GPIO_INPUT_FLOAT
#define PORTC_PIN13_CONFIG GPIO_INPUT_FLOAT
#define PORTC_PIN14_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTC_PIN15_CONFIG GPIO_INPUT_PULLUP_DOWN

/**
 * @ref PIN_LOCKING
 * to lock the pin on it's value (can't be changed until the next reset)
 */
#define PORTC_PIN0_LOCK GPIO_PIN_LOCKED
#define PORTC_PIN1_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN2_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN3_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN4_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN5_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN6_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN7_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN8_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN9_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN10_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN11_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN12_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN13_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN14_LOCK GPIO_PIN_UNLOCKED
#define PORTC_PIN15_LOCK GPIO_PIN_UNLOCKED

/**
 * @ref PORT_VALUES
 * SET PORT C PINS VALUES (IF PIN CONFIGURED AS OUTPUT)
 */
#define PORTC_PIN0_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN1_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN2_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN3_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN4_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN5_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN6_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN7_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN8_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN9_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN10_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN11_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN12_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN13_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN14_VALUE GPIO_OUTPUT_HIGH
#define PORTC_PIN15_VALUE GPIO_OUTPUT_HIGH
/***************************** PORT D *****************************************/
/**
 * @ref PORT_MODES
 * SET PORT D PINS MODES
 */
#define PORTD_PIN0_MODE GPIO_OUTPUT_10MHZ
#define PORTD_PIN1_MODE GPIO_OUTPUT_2MHZ
#define PORTD_PIN2_MODE GPIO_INPUT
#define PORTD_PIN3_MODE GPIO_OUTPUT_50MHZ
#define PORTD_PIN4_MODE GPIO_OUTPUT_50MHZ
#define PORTD_PIN5_MODE GPIO_OUTPUT_2MHZ
#define PORTD_PIN6_MODE GPIO_INPUT
#define PORTD_PIN7_MODE GPIO_INPUT
#define PORTD_PIN8_MODE GPIO_INPUT
#define PORTD_PIN9_MODE GPIO_OUTPUT_10MHZ
#define PORTD_PIN10_MODE GPIO_OUTPUT_2MHZ
#define PORTD_PIN11_MODE GPIO_OUTPUT_50MHZ
#define PORTD_PIN12_MODE GPIO_INPUT
#define PORTD_PIN13_MODE GPIO_INPUT
#define PORTD_PIN14_MODE GPIO_INPUT
#define PORTD_PIN15_MODE GPIO_INPUT

/**
 * @ref PORT_CONFIGURATION
 * SET PORT D PINS CONFIGURATION
 */
#define PORTD_PIN0_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTD_PIN1_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTD_PIN2_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTD_PIN3_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTD_PIN4_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTD_PIN5_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTD_PIN6_CONFIG GPIO_INPUT_FLOAT
#define PORTD_PIN7_CONFIG GPIO_INPUT_FLOAT
#define PORTD_PIN8_CONFIG GPIO_INPUT_FLOAT
#define PORTD_PIN9_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTD_PIN10_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTD_PIN11_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTD_PIN12_CONFIG GPIO_INPUT_FLOAT
#define PORTD_PIN13_CONFIG GPIO_INPUT_FLOAT
#define PORTD_PIN14_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTD_PIN15_CONFIG GPIO_INPUT_PULLUP_DOWN

/**
 * @ref PIN_LOCKING
 * to lock the pin on it's value (can't be changed until the next reset)
 */
#define PORTD_PIN0_LOCK GPIO_PIN_LOCKED
#define PORTD_PIN1_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN2_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN3_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN4_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN5_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN6_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN7_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN8_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN9_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN10_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN11_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN12_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN13_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN14_LOCK GPIO_PIN_UNLOCKED
#define PORTD_PIN15_LOCK GPIO_PIN_UNLOCKED

/**
 * @ref PORT_VALUES
 * SET PORT D PINS VALUES (IF PIN CONFIGURED AS OUTPUT)
 */
#define PORTD_PIN0_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN1_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN2_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN3_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN4_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN5_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN6_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN7_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN8_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN9_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN10_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN11_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN12_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN13_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN14_VALUE GPIO_OUTPUT_HIGH
#define PORTD_PIN15_VALUE GPIO_OUTPUT_HIGH
/***************************** PORT E *****************************************/
/**
 * @ref PORT_MODES
 * SET PORT E PINS MODES
 */
#define PORTE_PIN0_MODE GPIO_OUTPUT_10MHZ
#define PORTE_PIN1_MODE GPIO_OUTPUT_2MHZ
#define PORTE_PIN2_MODE GPIO_INPUT
#define PORTE_PIN3_MODE GPIO_OUTPUT_50MHZ
#define PORTE_PIN4_MODE GPIO_OUTPUT_50MHZ
#define PORTE_PIN5_MODE GPIO_OUTPUT_2MHZ
#define PORTE_PIN6_MODE GPIO_INPUT
#define PORTE_PIN7_MODE GPIO_INPUT
#define PORTE_PIN8_MODE GPIO_INPUT
#define PORTE_PIN9_MODE GPIO_OUTPUT_10MHZ
#define PORTE_PIN10_MODE GPIO_OUTPUT_2MHZ
#define PORTE_PIN11_MODE GPIO_OUTPUT_50MHZ
#define PORTE_PIN12_MODE GPIO_INPUT
#define PORTE_PIN13_MODE GPIO_INPUT
#define PORTE_PIN14_MODE GPIO_INPUT
#define PORTE_PIN15_MODE GPIO_INPUT

/**
 * @ref PORT_CONFIGURATION
 * SET PORT E PINS CONFIGURATION
 */
#define PORTE_PIN0_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTE_PIN1_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTE_PIN2_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTE_PIN3_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTE_PIN4_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTE_PIN5_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTE_PIN6_CONFIG GPIO_INPUT_FLOAT
#define PORTE_PIN7_CONFIG GPIO_INPUT_FLOAT
#define PORTE_PIN8_CONFIG GPIO_INPUT_FLOAT
#define PORTE_PIN9_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTE_PIN10_CONFIG GPIO_OUTPUT_PUSHPULL
#define PORTE_PIN11_CONFIG GPIO_OUTPUT_OPENDRAIN
#define PORTE_PIN12_CONFIG GPIO_INPUT_FLOAT
#define PORTE_PIN13_CONFIG GPIO_INPUT_FLOAT
#define PORTE_PIN14_CONFIG GPIO_INPUT_PULLUP_DOWN
#define PORTE_PIN15_CONFIG GPIO_INPUT_PULLUP_DOWN

/**
 * @ref PIN_LOCKING
 * to lock the pin on it's value (can't be changed until the next reset)
 */
#define PORTE_PIN0_LOCK GPIO_PIN_LOCKED
#define PORTE_PIN1_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN2_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN3_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN4_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN5_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN6_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN7_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN8_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN9_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN10_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN11_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN12_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN13_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN14_LOCK GPIO_PIN_UNLOCKED
#define PORTE_PIN15_LOCK GPIO_PIN_UNLOCKED

/**
 * @ref PORT_VALUES
 * SET PORT E PINS VALUES (IF PIN CONFIGURED AS OUTPUT)
 * if the corresponding pin is input, then set it to pull_up or pull_down
 */
#define PORTE_PIN0_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN1_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN2_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN3_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN4_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN5_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN6_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN7_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN8_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN9_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN10_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN11_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN12_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN13_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN14_VALUE GPIO_OUTPUT_HIGH
#define PORTE_PIN15_VALUE GPIO_OUTPUT_HIGH

#endif
