/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Inc/MCAL/RCC/RCC_interface.h"

#include "../Inc/MCAL/GPIO/GPIO_config.h"
#include "../Inc/MCAL/GPIO/GPIO_interface.h"

#include "../Inc/MCAL/NVIC/NVIC_config.h"
#include "../Inc/MCAL/NVIC/NVIC_interface.h"

#include "../Inc/MCAL/EXTI/EXTI_config.h"
#include "../Inc/MCAL/EXTI/EXTI_interface.h"

#include "../Inc/MCAL/SysTick/SysTick_interface.h"

#include "../Inc/HAL/LED/LED_interface.h"
#include "../Inc/HAL/SWITCH/SW_interface.h"
#include "../Inc/HAL/SEVEN_SEGMENT/SEVSEG_interface.h"
#include "../Inc/HAL/LCD/LCD_interface.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile void delay1s(uint32_t ms){
    // Calculate the number of cycles per millisecond
    uint32_t cycles = (32000000 / 1000) * ms;

    // Use a volatile variable to prevent optimization
    volatile uint32_t counter = 0;

    // Wait for the specified number of cycles
    while (counter < cycles) {
        counter++;
    }
}


void toggleB0_1s(void* none){
  // toggle pin 0 in port B every 20ms for 5 times
  for(volatile uint8_t i = 0; i < 5; i++){
    delay1s(1000);
    GPIO_enuTogglePinValue(GPIO_PORTB, GPIO_PIN_0);
  }
}

void toggleB1_1s(void* none){
  // toggle pin 1 in port B every 20ms for 5 times
  for(volatile uint8_t i = 0; i < 5; i++){
    delay1s(1000);
    GPIO_enuTogglePinValue(GPIO_PORTB, GPIO_PIN_2);
  }
}

void commons_update(uint8_t en_com, uint8_t digit);
int main(void)
{
	RCC_vidInit();
	//GPIO_vidInit();
	RCC_enuEnablePeripheralClock(APB_2_ID, IO_PORTA_ID);
	RCC_enuEnablePeripheralClock(APB_2_ID, IO_PORTB_ID);
	SEVSEG_enuInit();
	LCD_enuInit();
	GPIO_enuSetPinConfiguration(GPIO_PORTB, GPIO_PIN_11, &(GPIO_PinConfig_t){GPIO_OUTPUT_10MHZ, GPIO_OUTPUT_PUSHPULL, GPIO_OUTPUT_LOW});
	for(;;){
		SysTick_vidDelayMs(5);
		GPIO_enuSetPinValue(GPIO_PORTB, GPIO_PIN_11, GPIO_OUTPUT_HIGH);
		SysTick_vidDelayMs(5);
		GPIO_enuSetPinValue(GPIO_PORTB, GPIO_PIN_11, GPIO_OUTPUT_LOW);
		 for(uint32_t i = 0; i <= 99999999; i++){
		 	LCD_enuSendCommand(CLEAR_DISPLAY_CMD);
		 	LCD_enuDisplayInteger((sint64_t) i);
		 	for(uint32_t j = 0; j < 5; j++){
				commons_update(3, i%10);
				commons_update(2, (i/10)%10);
				commons_update(1, (i/100)%10);
				commons_update(0, (i/1000)%10);
		 	}
		 }
	}
}

void commons_update(uint8_t en_com, uint8_t digit){
	SEVSEG_enuDisableCommon((en_com+1)%4);
	SEVSEG_enuDisplayDigit(en_com, digit);
	SEVSEG_enuEnableCommon(en_com);
	SysTick_vidDelayMs(5);
}
