/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Inc/MCAL/RCC/RCC_interface.h"

#include "../Inc/MCAL/GPIO/GPIO_config.h"
#include "../Inc/MCAL/GPIO/GPIO_interface.h"

#include "../Inc/MCAL/NVIC/NVIC_config.h"
#include "../Inc/MCAL/NVIC/NVIC_interface.h"

#include "../Inc/MCAL/EXTI/EXTI_config.h"
#include "../Inc/MCAL/EXTI/EXTI_interface.h"

#include "../Inc/MCAL/UART/UART_config.h"
#include "../Inc/MCAL/UART/UART_interface.h"

#include "../Inc/MCAL/SysTick/SysTick_interface.h"

#include "../Inc/HAL/LED/LED_interface.h"
#include "../Inc/HAL/SWITCH/SW_interface.h"
#include "../Inc/HAL/SEVEN_SEGMENT/SEVSEG_interface.h"
#include "../Inc/HAL/LCD/LCD_interface.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void send_data(void * ptr){
  uint8_t str[20] = "I LOVE GHARAM\n";
  UART_enuTransmitString(UART_1, UART_POLLING_ENABLE, str);
}


int main(void)
{
  RCC_vidInit();
  RCC_enuEnablePeripheralClock(APB_2_ID, AFIO_ID);
//  GPIO_vidInit();
  UART_enuInit(UART_1);
  EXTI_enuInit();
  LCD_enuInit();
  void* ptr;
  EXTI_enuSetInterruptHandler(EXTI_LINE1, &send_data, &ptr);
  uint8_t str[100];
	while(1){
		UART_enuReceiveString(UART_1, UART_POLLING_ENABLE, str);
		LCD_enuSendCommand(CLEAR_DISPLAY_CMD);
		LCD_enuDisplayString(str);
		SysTick_vidDelayMs(500);
	}
}
