/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Inc/MCAL/RCC/RCC_interface.h"

#include "../Inc/MCAL/GPIO/GPIO_config.h"
#include "../Inc/MCAL/GPIO/GPIO_interface.h"

#include "../Inc/MCAL/NVIC/NVIC_config.h"
#include "../Inc/MCAL/NVIC/NVIC_interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	RCC_vidInit();
	GPIO_vidInit();
	GPIO_enuSetPinConfiguration(GPIO_PORTA,GPIO_PIN_0, &(GPIO_PinConfig_t){
		.mode = GPIO_OUTPUT_2MHZ,
		.config = GPIO_OUTPUT_OPENDRAIN,
		.value = GPIO_OUTPUT_LOW
	});
	for(uint8_t i = 0; i < 16; i++){
		GPIO_enuSetPinConfiguration(GPIO_PORTA, i, &(GPIO_PinConfig_t){
			.mode = GPIO_OUTPUT_2MHZ,
			.config = GPIO_OUTPUT_PUSHPULL,
			.value = GPIO_OUTPUT_LOW
		});
	}

	GPIO_enuLockPin(GPIO_PORTA, GPIO_PIN_5);
	GPIO_enuLockPin(GPIO_PORTA, GPIO_PIN_9);
	GPIO_enuLockPin(GPIO_PORTA, GPIO_PIN_12);

	NVIC_vidInit();
    /* Loop forever */
	for(;;){
		for(uint8_t i = 0; i < 16; i++){
			GPIO_enuSetPinValue(GPIO_PORTA, i, GPIO_OUTPUT_HIGH);
			for(uint32_t j = 0; j < 10000; j++);
		}

		for(uint8_t i = 0; i < 16; i++){
			GPIO_enuSetPinValue(GPIO_PORTA, i, GPIO_OUTPUT_LOW);
			for(uint32_t j = 0; j < 10000; j++);
		}
	}
}
